### PR TITLE
Last PR (dev into master)

### PR DESCRIPTION
**Pull request by LudovicLanchon**
## TO VALID PR

* All commits, vars, documentation, code are in English
* 1 feature = 1 PR, No more
* The code builds with Travis CI, and nothing looks unfinished
* When code is complicated, that’s documented, otherwise ask for comment 
* No node_modules is present
* Code respect [Airbnb style](https://hackernoon.com/configure-eslint-prettier-and-flow-in-vs-code-for-react-development-c9d95db07213) checked with Travis CI
* README explain Clearly how to run the project, otherwise reject the PR
* Chrome LightHouse CI score is upper than 80%

### CODE REVIEW

**Review by oceaneduble — APPROVED** [review]
Ok

**Review by GBellamy — APPROVED** [review]
seems good :)

**Review by CastellierGwenole — APPROVED** [review]
!

**Review by GuillaumeCabaret — APPROVED** [review]
OMG OMG SO GOOD

**Review by paulMorea — APPROVED** [review]
good

**Pull request merged**
