### PR TITLE
Dev on master

### PR DESCRIPTION
**Pull request by LudovicLanchon**
Sorry for this long PR

## TO VALID PR

* All commits, vars, documentation, code are in English
* 1 feature = 1 PR, No more
* The code builds with Travis CI, and nothing looks unfinished
* When code is complicated, that’s documented, otherwise ask for comment 
* No node_modules is present
* Code respect [Airbnb style](https://hackernoon.com/configure-eslint-prettier-and-flow-in-vs-code-for-react-development-c9d95db07213) checked with Travis CI
* README explain Clearly how to run the project, otherwise reject the PR
* Chrome LightHouse CI score is upper than 80%

### CODE REVIEW

**Review by oceaneduble — APPROVED** [review]
Good

**Review by GuillaumeCabaret — APPROVED** [review]
seems good for me

**Review by GBellamy — APPROVED** [review]
Seems good to me

**Review by ctoxy — APPROVED** [review]
nice work

**Review by ArnaudPichot — APPROVED** [review]
osef

**Review by AvelJonathan — APPROVED** [review]

**Pull request merged**
