### PR TITLE
Third PR (redesign)

### PR DESCRIPTION
**Pull request by LudovicLanchon**
Redesign some buttons and the game page

## TO VALID PR

* All commits, vars, documentation, code are in English
* 1 feature = 1 PR, No more
* The code builds with Travis CI, and nothing looks unfinished
* When code is complicated, that’s documented, otherwise ask for comment 
* No node_modules is present
* Code respect [Airbnb style](https://hackernoon.com/configure-eslint-prettier-and-flow-in-vs-code-for-react-development-c9d95db07213) checked with Travis CI
* README explain Clearly how to run the project, otherwise reject the PR
* Chrome LightHouse CI score is upper than 80%

### CODE REVIEW

**Review by GuillaumeCabaret — APPROVED** [review]
clear changes

**Review by ArnaudPichot — APPROVED** [review]
good continuation ;)

**Review by Menthx — APPROVED** [review]
Ok très bien !

**Review by oceaneduble — APPROVED** [review]
Good

**Review by AvelJonathan — APPROVED** [review]
Your PR is pretty long but well , it's same for us...

I don't see any problems in the code, good luck for the game !

**Pull request merged**
